[book]
title = "Notes"
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/notes.css", "theme/hub.css"]

[output.html.search]
enable = false

[output.html.print]
enable = false
